GET http://localhost:3000/api/clientes

###

GET http://localhost:3000/api/clientes  
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw
###


GET http://localhost:3000/api/clientes/profile  
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw
###


post http://localhost:3000/api/clientes/update  
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw

{
    "nombre": "Jorge",
    "username": "Jorgito",
    "email": "jj@gmail.com",
    "photo": "https://cdn.domestika.org/c_limit,dpr_auto,f_auto,q_auto,w_820/v1552473155/content-items/002/854/613/IMG_2802-original.jpg?1552473155",
    "textProfile": "esto funciona"
}


###
// comienzo de las peticiones Users
POST  http://localhost:3000/api/users/create
Content-Type: application/json

{
    "nombre": "Jorge",
    "username": "Jorgito",
    "password": "1345",
    "email": "jj@gmail.com"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json


{
    "email": "jj@gmail.com",
    "password": "1345"
}
// final de las peticiones users
###
// comienzo de las peticiones POST
GET http://localhost:3000/api/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw


###

post http://localhost:3000/api/posts/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw

{
    "date":"2021-06-05",
    "idTypePost":1,
    "photoPost":"https://images.unsplash.com/photo-1639669047277-32640a26bdf6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    "usuario_id":12
}

###
GET http://localhost:3000/api/posts/user/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw


###
DELETE http://localhost:3000/api/posts/id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw

{
    "id": 1
}
// final de las peticiones post

// comienzo de las peticiones Likes

###
GET  http://localhost:3000/api/likes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw


###

POST http://localhost:3000/api/likes/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw

{
    "idlike": 7,
    "idPost": 7,
    "date":"2019-06-06",
    "usuario_id": 7
}

###

GET  http://localhost:3000/api/likes/id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw

{
    "idlike": 7
   
}

###

DELETE  http://localhost:3000/api/likes/id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjgsImV4cGlyZWRBdCI6MTY0MDQyNTc4MywiaWF0IjoxNjM5OTkzNzgzfQ.JQtkJvUrLJ9eWUGKARliwl497hCni4sVCF6dNgcc9Bw

{
    "idlike": 6
    
}
// final de las peticiones likes



